### ISSUE TITLE
Problem with obfuscate

### ISSUE THREAD

**Issue by vipien** [JdeH/Opy#3]
![problem](https://cloud.githubusercontent.com/assets/8376694/13190291/8859f07c-d72e-11e5-9efc-4acbbb17b2a4.PNG)

Hello, im trying to obfuscate my code but but I get an error

**Comment by vipien** [comment]
Sorry, my problem was that I had Latin-1 encoding

**Comment by JdeH** [comment]
Hi

I thought something like that, but didn't yet find the time to try.

Kind regards
Jacques
