### ISSUE TITLE
File names are change.

### ISSUE THREAD

**Issue by ccfiel** [JdeH/Opy#5]
File name of my .py is changes to l11l11lll_opy_.py, l11l11111_opy_.py, l11lll111_opy_.py and etc. I have   3 py files what is needs to be executed. How will I know which is it? Its been obfuscated. Any ideas?

**Comment by JdeH** [comment]
The names of modules are obfuscated. So if you have a file my_module.py and you import it somewhere with "import my_module", the import and the filename are e.g. changed to l1l11.py and "import l1l11". There's no easy way to find out which file is which, that's exactly the purpose of the obfuscation.

If you still want to find out which file is which, put a non-obfuscated string into the module with its name. But in general, the less easy it is to decipher what is what, the better the obfuscation works.

**Comment by ccfiel** [comment]
@JdeH  Thanks for the reply.

If I have 
main.py --- the executable script
module.py --- the script used (import) by main.py

So I have to do is obfuscated module.py and exclude main.py. Is it the right way to obfuscated?

In my opy_config.txt

```
plain_files = '''
opy_config.txt
main.py
'''

```

**Comment by JdeH** [comment]
No, you have to do:

`plain_names = '''
    main
'''`

**Comment by ccfiel** [comment]
@JdeH 

Thanks!

**Comment by JdeH** [comment]
Sorry to confuse you with mistake in my first answer, have editted accordingly.

**Comment by ccfiel** [comment]
No worries ☺
