### ISSUE TITLE
Obfuscate string variables only

### ISSUE THREAD

**Issue by pete111** [JdeH/Opy#7]
Hello, 
please, is there any way how to obfuscate content of string variables?
I would like to obfuscate only content of string variables (only variables, not functions, classes, etc) and other variables should be left untouched. Thank you!

```
myvariable1 = "should be obfuscated"
myvariable2 = 'should be obfuscated'
myvariable3 = glob.glob #should not be obfuscated
```

**Comment by JdeH** [comment]
Hi Pete

I am sorry but there's currently no way to obfuscate only string vars.

Kind regards
Jacques
